name: Lint and Style Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Run Linters and Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check component file extensions
        run: |
          # Files that should use .jsx extension
          COMPONENT_PATHS=(
            "src/common/components"
            "src/pages"
            "src/App.jsx"
          )

          # Find .js files in component directories (excluding specific patterns)
          INVALID_FILES=$(find "${COMPONENT_PATHS[@]}" -type f \
            -name "*.js" \
            ! -name "*.test.js" \
            ! -name "styles.js" \
            ! -name "*.config.js" \
            ! -name "*.utils.js" \
            ! -name "*.constants.js" \
            2>/dev/null || true)

          if [ ! -z "$INVALID_FILES" ]; then
            echo "The following files should use .jsx extension:"
            echo "$INVALID_FILES"
            echo "Components, pages, and App should use .jsx extension"
            exit 1
          fi

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Verify import sorting
        run: npm run check-imports
