name: Lint and Style Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Run Linters and Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check file extensions
        run: |
          if find src -type f -name "*.js" ! -name "*.test.js" ! -name "setupTests.js" ; then
            echo "Found .js files that should be .jsx"
            exit 1
          fi

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Verify import sorting
        run: npm run check-imports
